hoten=input("Ho ten: ")
snc=int(input("So ngay cong: "))
Dg=int(input("Don gia ngay cong: "))
Hs=float(input("He so phu cap: "))
u=int(input("Tam ung: "))
print("Nhan vien "+hoten+","+" Co tien luong="+str(Dg*snc*Hs)+","+" Tam ung="+str(u)+" va Thuc linh="+str(Dg*snc*Hs-u))